<?php

namespace app\admin\controller;

use think\Db;
use think\Loader;

class Config extends Base
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = 'config';
    }

    public function index()
    {
        if (request()->isPost()) {
            $page = $this->page;
            $limit = $this->limit;
            $limit = ($page - 1) * $limit . ",$limit";
            $sql = "select * from cg_config where `key` not in ('appid','appsecret','mch_id','key') order by id desc limit $limit";
            $list = Db::query($sql);
            $count = Db::query("select count(*) as count from cg_config where `key` not in ('appid','appsecret','mch_id','key')")[0]['count'];
            success_callback('', ['count' => $count, 'list' => $list]);
            exit;
        }
        return view();
    }

    public function add()
    {
        if (request()->isPost()) {
            $params = input('post.');
            $data['value'] = !empty($params['info1']) ? $params['info1'] : $params['info2'];
            if(empty($data['value'])){
                error_callback();exit;
            }
            $data['key'] = $params['key'];
            $data['remarks'] = $params['remarks'];
            $this->common->insert_one($this->model, $data);
        }
        return view();
    }

    public function edit($id){
        if(request()->isPost()){
            $params = input('post.');
            $data['value'] = !empty($params['info1']) ? $params['info1'] : $params['info2'];
            if(empty($data['value'])){
                error_callback();exit;
            }
            $data['id'] = $params['id'];
            $data['key'] = $params['key'];
            $data['remarks'] = $params['remarks'];
            $this->common->save_one($this->model,$data);
        }
        $info=$this->common->get_find($this->model,$id);
        $info['ue'] = 0;
        if(in_array($info['key'],['about_us','use_to_know','fuwuxieyi'])){
            $info['ue'] = 1;
        }
        return view('',[
            'info'=>$info
        ]);
    }
    public function delete($id=""){
        if($id!=""){
            $this->common->delete($this->model,$id);
        }
    }
}