<?php


namespace app\admin\controller;


class ContentLink extends Base
{
    public function _initialize()
    {
        $this->assign('meta_title', '关键词列表');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return view('');
    }

    public function data()
    {
        if(request()->isPost()) {
            $page = request()->post('page', 1);
            $limit = request()->post('limit', 10);
            $keyword = request()->post('keyword');
            $contentLink = model('ContentLink');
            $map = ['status'=>1];
            $offset = ($page - 1) * $limit;
            if(!empty($keyword)) {
                $map['keyword'] = ['like', $keyword];
            }
            $data = $contentLink->where($map)->order('id desc')->limit($offset, $limit)->select();
            foreach ($data as $key => $val) {
                $val['key'] = $offset + 1 + $key;
                $data[$key] = $val;
            }
            $count = $contentLink->where($map)->count();
            return json(['data'=>['count'=>$count, 'list'=>$data]], 200);
        }
    }

    public function create()
    {
        if(request()->isPost()) {
            $contentLink = model('ContentLink');
            $_post = request()->post();
            $state = $contentLink->allowField(true)->save($_post);
            if($state !== false) {
                return success_json('添加成功');
            }
            return success_json('添加失败');
        }
        return view('');
    }

    public function edit($id)
    {
        $contentLink = model('ContentLink');
        if(request()->isPost()) {
            $_post = request()->post();
            $state = $contentLink->allowField(true)->save($_post, ['id' => $id]);
            if($state !== false) {
                return success_json('编辑成功');
            }
            return success_json('编辑失败');
        }
        $info = $contentLink->find($id);
        return view('', ['data' => $info]);
    }

    public function delete($id)
    {
        $contentLink = model('ContentLink');
        $state = $contentLink->allowField(true)->save(['status' => 0], ['id' => $id]);
        if($state !== false) {
            return success_json('删除成功');
        }
        return success_json('删除失败');
    }

}