<?php
namespace app\admin\controller;

class PackagePrice extends Base
{
    public $type = array(
        array('id'=>1, 'title'=>'月'),
        array('id'=>2, 'title'=>'季'),
        array('id'=>3, 'title'=>'年'),
    );

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if(request()->isPost()) {
            $page = request()->post('page', 1);
            $limit = request()->post('limit', 10);
            $offset = ($page - 1) * $limit;
            $PackagePrice = model('PackagePrice');
            $package = model('package');
            $map = ['A.status'=>1];
            $data = $PackagePrice->alias('A')
                ->join($package->getTable().' B', 'A.package_id=B.id', 'left')
                ->field('A.*,B.title as package_title')
                ->where($map)->order('id desc')->limit($offset, $limit)->select();
            foreach ($data as $k => $v) {
                $v['key'] = $k+ ($page-1)*$limit+1;
                $data[$k] = $v;
            }
            $count = $PackagePrice->alias('A')
                ->join($package->getTable().' B', 'A.package_id=B.id', 'left')
                ->where($map)->count();
            return json(['data' => [ 'count' => $count, 'list' => $data]], 200);
        }
        return view('', []);
    }

    public function create()
    {
        if(request()->isPost()) {
            $_post = request()->post();
            $PackagePrice = model('PackagePrice');
            $state = $PackagePrice->allowField(true)->save($_post);
            if($state !== false) {
                return success_json('添加成功');
            }
            return error_json('添加失败');
        }
        $packageInfo = model('package')->where(['status'=>1])->select();
        return view('', [
            'type' => $this->type,
            'info' => $packageInfo,
        ]);
    }

    public function edit($id)
    {
        $PackagePrice = model('PackagePrice');
        if(request()->isPost()) {
            $_post = request()->post();
            $state = $PackagePrice->allowField(true)->isUpdate(true)->save($_post, ['id'=>$id]);
            if($state !== false) {
                return success_json('编辑成功');
            }
            return error_json('编辑失败');
        }
        $packageInfo = model('package')->where(['status'=>1])->select();
        $data = $PackagePrice->find($id);
        return view('', [
            'type' => $this->type,
            'info' => $packageInfo,
            'data' => $data
        ]);
    }

    public function delete($id)
    {
        $PackagePrice = model('PackagePrice');
        $state = $PackagePrice->allowField(true)->isUpdate(true)->save(['status' => 0], ['id' => $id]);
        if($state !== false) {
            return success_json('删除成功');
        }
        return error_json('删除失败');
    }

}