<?php
namespace app\admin\controller;

class PayConfig extends Base
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if(request()->isPost()) {
            $page = request()->post('page', 1);
            $limit = request()->post('limit', 10);
            $offset = ($page - 1) * $limit;
            $PayConfig = model('PayConfig');
            $map = ['A.status'=>1];
            $data = $PayConfig->alias('A')
                ->where($map)->order('id desc')->limit($offset, $limit)->select();
            foreach ($data as $k => $v) {
                $v['key'] = $k+ ($page-1)*$limit+1;
                $data[$k] = $v;
            }
            $count = $PayConfig->alias('A')
                ->where($map)->count();
            return json(['data' => [ 'count' => $count, 'list' => $data]], 200);
        }
        return view('', []);
    }

    public function create()
    {
        if(request()->isPost()){
            $PayConfig = model('PayConfig');
            $_post = request()->post();
            $state = $PayConfig->allowField(true)->save($_post);
            if($state !== false) {
                return success_json('新建成功');
            }
            return error_json('新建失败');
        }
        return view('', []);
    }

    public function edit($id)
    {
        $PayConfig = model('PayConfig');
        if(request()->isPost()){
            $_post = request()->post();
            $state = $PayConfig->allowField(true)->save($_post, ['id'=>$id]);
            if($state !== false) {
                return success_json('编辑成功');
            }
            return error_json('编辑失败');
        }
        $data = $PayConfig->find($id);
        return view('', ['data'=>$data]);
    }

    public function delete($id)
    {
        $PayConfig = model('PayConfig');
        $state = $PayConfig->allowField(true)->save(['status' => 0], ['id' => $id]);
        if($state !== false) {
            return success_json('删除成功');
        }
        return error_json('删除失败');
    }

}